import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { Roboto as FontRoboto } from "next/font/google";
import { Open_Sans as FontOpenSans } from "next/font/google";
import { Lato as FontLato } from "next/font/google";
import React from 'react';

import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/shared/Navbar";

// Configure each font
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontRoboto = FontRoboto({
  subsets: ["latin"],
  variable: "--font-roboto",
});

const fontOpenSans = FontOpenSans({
  subsets: ["latin"],
  variable: "--font-open-sans",
});

const fontLato = FontLato({
  subsets: ["latin"],
  variable: "--font-lato",
});

// Metadata for the application
export const metadata: Metadata = {
  title: "Priyansh Chauhan",
  description: "Generated by create next app",
};

// RootLayout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(fontOpenSans.variable, fontRoboto.variable, fontLato.variable)}>
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable // Apply Inter font (fontSans) to body
      )}>
        <Navbar />
        {React.cloneElement(children, {
          fontSans: fontSans.variable,
          fontRoboto: fontRoboto.variable,
          fontOpenSans: fontOpenSans.variable,
          fontLato: fontLato.variable,
        })}
      </body>
    </html>
  );
}
